Update to OD 11.5 and backport from OCP branch
ObeoNetwork/Flow-Designer pull request #19
Opened 2021-08-26 09:50 UTC by adaussy

2021-09-22 20:34 UTC, pcdavid requested changes
OK for almost all the changes, but in the flow.odesign changes (more precisely in the Topography diagram) there are some that I'm not sure about:
* it seems the whole "Temperature" and "Power" layers have disappeared;
* in the old version, the "System" mapping _reused_ the "Data Source" one, but in the new version "Data Source" is duplicated (which means "Data Source to Processor" has to refer to both instances).
* the newly added "Fan" mapping inside "System" uses `aql:self.eAllContents(flow::Fan)` as a semantic candidates expression. This does not seem right as a system can contain sub-systems recursively, but I don't see why all the fans inside a system's descendants should appear in it.
* it looks like the cpu.svg file has been removed, but it is used as the default for the "Processor" mapping.

2021-09-23 14:32 UTC, ejuliot commented
After my test, I detect several issues in the odesign:
- Topography/System/DataSource/workspace style: aql:self.name+': ' +self.volume should be aql:self.name+' : ' +self.volume  to support direct edit
- Topography/Tools/DataSource : Nodemapping should concerns the two kind of DataSource (outside and inside a system)
- Fan should be move to a dedicated layer (so, with a container import for system), to support the demo scenario

2021-09-27 09:35 UTC, ejuliot commented
I have a blocking bug: when I change a value of an element which has a conditional style to change the size according this value, the first change makes the SVG very large (wider than the container). Then, a second update of the value makes it at the right size.
It can be tested with Fan / speed and Processor / capacity.

It is blocking as it makes demo too buggy.

2021-09-27 09:40 UTC, ejuliot commented on README.md
> +To install it, the easiest way is to download Obeo Designer Community Edition 11.5.0 which provides a ready-to-use bundle with Sirius 6.5.1. Just check out this source code, and use a runtime workspa
You should add a direct link to https://www.obeodesigner.com/en/download.

Then, the installation is not so trivial. There are two options : one with Xtext (so, explain how to install XText from the marketplace or the OD updatesite with "Sirius Integration with Xtext", and another without Xtext (so, just explain to not import some projects).

2021-09-27 13:33 UTC, adaussy commented
> 
> 
> OK for almost all the changes, but in the flow.odesign changes (more precisely in the Topography diagram) there are some that I'm not sure about:
> 
>     * it seems the whole "Temperature" and "Power" layers have disappeared;

Done
> 
>     * in the old version, the "System" mapping _reused_ the "Data Source" one, but in the new version "Data Source" is duplicated (which means "Data Source to Processor" has to refer to both instances).
> 

Done
>     * the newly added "Fan" mapping inside "System" uses `aql:self.eAllContents(flow::Fan)` as a semantic candidates expression. This does not seem right as a system can contain sub-systems recursively, but I don't see why all the fans inside a system's descendants should appear in it.

Done

> 
>     * it looks like the cpu.svg file has been removed, but it is used as the default for the "Processor" mapping.

Yes however I think that all conditional style should cover all cases. But I will add it back to be sure.

2021-09-27 13:34 UTC, adaussy commented
> 
> 
> After my test, I detect several issues in the odesign:
> 
>     * Topography/System/DataSource/workspace style: aql:self.name+': ' +self.volume should be aql:self.name+' : ' +self.volume  to support direct edit

Done

> 
>     * Topography/Tools/DataSource : Nodemapping should concerns the two kind of DataSource (outside and inside a system)
> 
Done

>     * Fan should be move to a dedicated layer (so, with a container import for system), to support the demo scenario

Done

2021-10-04 08:38 UTC, adaussy commented
> 
> 
> I have a blocking bug: when I change a value of an element which has a conditional style to change the size according this value, the first change makes the SVG very large (wider than the container). Then, a second update of the value makes it at the right size. It can be tested with Fan / speed and Processor / capacity.
> 
> It is blocking as it makes demo too buggy.

In progress of reporting a bug

2021-10-04 09:21 UTC, adaussy commented
> 
> 
> > I have a blocking bug: when I change a value of an element which has a conditional style to change the size according this value, the first change makes the SVG very large (wider than the container). Then, a second update of the value makes it at the right size. It can be tested with Fan / speed and Processor / capacity.
> > It is blocking as it makes demo too buggy.
> 
> In progress of reporting a bug

Here are the matching bugs:

* https://github.com/ObeoNetwork/Flow-Designer/issues/20 
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=576423

2021-11-15 10:31 UTC, lredor approved these changes

2021-11-15 10:35 UTC, lredor approved these changes

2021-11-15 10:37 UTC, lredor approved these changes

2021-11-15 10:39 UTC, lredor reviewed
Whoops. I thought I approved each commit individually. This is not the case. And currently, I've not finished the reviewe...

2021-11-17 13:34 UTC, lredor requested changes
I think that it will be better to have a prefix for all commits (like in [Sirius contributor guide](https://wiki.eclipse.org/Sirius/Contributor_Guide#Commit_Messages_Formatting), for example). Here is the commits list of this PR (with a "**TO_UPDATE**" prefix in front of commit messages to update):
**TO_UPDATE** [releng] Update target platform to OD 11.5
**TO_UPDATE** [releng] Fix feature version for compliance
**TO_UPDATE** [cleanup] Regen MM using EMF version from OD 11.5
**TO_UPDATE** [cleanup] Add missing .gitignore for xtend generated sources
**TO_UPDATE** [releng] Add missing .project for the feature
**TO_UPDATE** [cleanup] Add Xtext nature for the target platform DSL use
**TO_UPDATE** [cleanup] Updates resulting from update of Acceleo
**TO_UPDATE** [cleanup] Update Sample model with latest Sirius Version
**TO_UPDATE** [BackportOCP] Update MM, VSM and regenerate
Non exhaustive list of changes:
* Add some new colors in the palette
* Add some direct edit tools
* Move Link from Power layer to default layer
* Change Fan size computation expression
* Update svg files
* Change default fan speed (1000 instead of 100)
* Made CapacityBound abstract

[BackportOCP] Update sample with new changes
**TO_UPDATE** [BackportOCP] Improve icons 
**TO_UPDATE** [BackportOCP] Replace 2 static SVG by animated SVG
[BackportOCP] Switch to Tycho 1.7.0
[BackportOCP] Use the recommended load options for faster model loading 
**TO_UPDATE** [doc] Update readme

2021-11-17 13:34 UTC, lredor commented on features/fr.obeo.dsl.designer.sample.flow.design.feature/.project
> +		<nature>org.eclipse.m2e.core.maven2Nature</nature>
This nature and associated buildCommand is not mandatory. It can be removed in another commit.

2021-11-17 13:34 UTC, lredor commented on plugins/fr.obeo.desl.designer.sample.flow.gen.java/tasks/generateJava.xml
> -    <property name="ECLIPSE_HOME" value="../../../../../demo/od/od 10.0/ObeoDesigner-Community"/>
This path is specific to your environment. Maybe a "more common" path will be better. This is not a mandatory change.

2021-11-17 13:34 UTC, lredor commented on plugins/fr.obeo.dsl.designer.sample.flow.gen.html/tasks/generateHTML.xml
> -    <property name="ECLIPSE_HOME" value="../../../../../demo/od/od 10.0/ObeoDesigner-Community"/>
Same remark than previous for path.

2021-11-17 13:34 UTC, lredor commented on plugins/fr.obeo.dsl.designer.sample.flow.design/description/flow.odesign
> -
It seems that there is no real change in this file (except a formatting change). So it is to remove and the commit description can be "[cleanup] Update Sample model with latest Sirius Version"

2021-11-17 13:34 UTC, lredor commented on plugins/fr.obeo.dsl.designer.sample.flow.edit/src-gen/fr/obeo/dsl/designer/sample/flow/provider/DataFlowItemProvider.java
> -		super.notifyChanged(notification);
If I generate with EMF 2.22 (the version of TP of OD 11.5), this line is not removed. Can you detail which version is used to generate?

2021-11-17 13:34 UTC, lredor commented on plugins/fr.obeo.dsl.designer.sample.flow.design/description/flow.odesign
> +        </edgeMappings>
It seems strange to have Link added here. It is already in the "Power" layer.

2021-11-17 13:34 UTC, lredor commented on plugins/fr.obeo.dsl.designer.sample.flow.design/description/flow.odesign
> +          </borderedNodeMappings>
Same remark than for Link edge. Why do you "duplicate" mappings from Power layer?

2021-11-17 13:34 UTC, lredor commented on samples/org.obeonetwork.sample.robot/representations.aird
> +      </ownedRepresentationDescriptors>
Not sure that we want this new representations. We already have existing representations (but with a "not deployed" odesign file). Furthermore, the existing representations are not refreshed according to "new changes" explained in commit description.

2022-01-06 13:10 UTC, adaussy commented on features/fr.obeo.dsl.designer.sample.flow.design.feature/.project
> +		<nature>org.eclipse.m2e.core.maven2Nature</nature>
Done

2022-01-06 13:11 UTC, adaussy commented on plugins/fr.obeo.desl.designer.sample.flow.gen.java/tasks/generateJava.xml
> -    <property name="ECLIPSE_HOME" value="../../../../../demo/od/od 10.0/ObeoDesigner-Community"/>
Not better not worst. keep that way

2022-01-06 13:11 UTC, adaussy commented on plugins/fr.obeo.dsl.designer.sample.flow.gen.html/tasks/generateHTML.xml
> -    <property name="ECLIPSE_HOME" value="../../../../../demo/od/od 10.0/ObeoDesigner-Community"/>
Not better not worst. keep that way

2022-01-06 13:20 UTC, adaussy commented on plugins/fr.obeo.dsl.designer.sample.flow.edit/src-gen/fr/obeo/dsl/designer/sample/flow/provider/DataFlowItemProvider.java
> -		super.notifyChanged(notification);
Done

2022-01-06 13:29 UTC, adaussy commented on plugins/fr.obeo.dsl.designer.sample.flow.design/description/flow.odesign
> +        </edgeMappings>
Done

2022-01-06 13:59 UTC, lredor approved these changes

2022-01-06 15:07 UTC, merged